{% set goname = "github.com/junegunn/fzf" %}
{% set version = "0.59.0" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: 72e1f94a74998dfaa38f9b24cabfe7b5c9f9303d8bb895eefbf55095f8f609db

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go build -ldflags "-X main.revision=conda-forge" -v -o $PREFIX/bin/fzf  # [not win]
    - go build -ldflags "-X main.revision=conda-forge" -v -o %LIBRARY_BIN%\fzf.exe  # [win]
    - bash -c "mkdir -p ${PREFIX}/share/fzf/shell; cp -v shell/* ${PREFIX}/share/fzf/shell/"
    - bash -c "mkdir -p ${PREFIX}/share/fzf/plugin; cp -v plugin/* ${PREFIX}/share/fzf/plugin/"
    - bash -c "mkdir -p ${PREFIX}/share/man/man1; cp -v man/man1/*.1 ${PREFIX}/share/man/man1/"
    - go-licenses save . --save_path ../../../../library_licenses
    # Clear out cache to avoid file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - fzf --version

about:
  home: https://{{ goname }}
  license: MIT
  license_family: MIT
  license_file:
    - {{ pkg_src }}/LICENSE
    - library_licenses/
  summary: A command-line fuzzy finder

extra:
  recipe-maintainers:
    - dbast
