travis:
  secure:
    BINSTAR_TOKEN: qFTJDexKoKlioqqI7xYFxt1DhrKHCDyST6OuGZ482suP4UwFaWNaAe2hF921ueCQwR6ZmkWSA7Ond4fMzVxpGb8jMC9yCx1Mv6Lyj6BvQtRDNgOrMOUWexcZoZ4PJNer9VsAXlOOZ1N6AyMo4gYPFBGX6EsQzPVq9NYWHVe85lUeO7HRA9qaSHLhOzf7+DEv0Gg6zrWREdDDxwmsg31g97X05FBXBU2ftzJix4icjAPqejoUqH/Up2btoWmdY36Q9oWkw7NNn46nzxccLRZu1TUfhW/ffINsrBXK3Q4zkozgE03/mlw78Vec32cGcbAx84zPqJNlwMpKXfcMX9AXj2yQz/LlVx3mrusjTRtJYtHBcimDLarDnq6b8zoSH33yQ20NXLzV99FNfEbPZzx8+qQcEEpRHfNkQV/rVoYub/TvkvB2tck/HPoNJV+UF6BmVkNIcX7Y77lyXQGz5BicZdj5R62ZQare2UbAMrl5yunFSboJ49vYpjUNzFqB3eGi3kb+3rARNsphCHlA+WXuxHn+n7GSOjuFM0fNjkfiF9S5DF+QgQMBx3EFwmRdzGIwaaeWdkYm+KExDFALU5E+1CA/M4X5ru4kRjaZ/pVO2qxOejQwg1+lUQvmzX3py4/sGsT/fHQvMANvreJloTP+cw426o+f4/Qmf5b7Yv2BfAY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
